version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres_customer_service
    restart: always
    environment:
      POSTGRES_DB: customer_service_db
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: sistem
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # RabbitMQ communication
      - "15672:15672"   # RabbitMQ management UI
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
