version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres_customer_service
    restart: always
    environment:
      POSTGRES_DB: customer_service_db
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: sistem
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

  customer-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customer_service
    depends_on:
      - postgres-db
      - rabbitmq
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/customer_service_db
      SPRING_DATASOURCE_USERNAME: alex
      SPRING_DATASOURCE_PASSWORD: sistem
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
